LEXICON_RU: dict[str, str] = {
    'no_answer':            'Данный тип апдейтов не поддерживается',
    'main_menu':            'это главное меню',
    'task_list':            "это меню всех заданий",
    'assignment_list':      "это меню всех назначений",
    'main':   "Главное меню админской стороны. \nДоступно: список заданий, добавление заданий, изменение заданий, назначение волонтеров",
    'main.tasks':               "Список заданий",
    'main.assignments':         "Assignments list",
    'main.assignments.list':    "Current assignments",
    'main.support':             "Support",
    'main.tasks.list':          "Current tasks",
    'task_creation.title':      "Please enter the task title:",
    'task_creation.description':"Please enter task description:",
    'task_creation.start_date': "Select start date:",
    'task_creation.time_format':"Please enter time in format HH:MM (e.g. 09:30):",
    'task_creation.start_date': "Select end date:",
    'task_creation.invalid_time_format':"Invalid time format! Please use HH:MM format (e.g. 09:30):",
    'task_edit.not_found':    "Задание не найдено",
    'main.assignments.create_assignemnt' : "Создаем назначение",
    'assignments_list': 'Список назначений',
    'create_assignment': 'Создать назначение',
    'select_task_for_assignment': 'Выберите задание для назначения',
    'main.volunteers':          "Волонтеры",
    'main.volunteers.add_volunteer': "Добавить волонтера",
    'main.volunteers.list':     "Список волонтеров",
    'task_list.select_day': "Выберите день для просмотра заданий:",
    'task_list.day_tasks': "📋 Задания на день {}\n\n"
}

LEXICON_RU_BUTTONS: dict[str, str] = {
    'main_menu':                "Главное меню",
    'go_back':                  "Назад",
    'task_list':                "Задания",
    'assignment_list':          "Назначения",
    'main.mytasks':             "My tasks",
    'main.spots':               "Spot tasks available",
    'main.faq':                 "FAQ",
    'main.mytasks.placeholder': "PLACEHOLDER FOR A TASK BUTTON",
    'main.faq.placeholder':     "PLACEHOLDER FOR A FAQ",
    'main.tasks':               "Список заданий",
    'main.assignments':         "Assignments list",
    'main.assignments.list':    "Current assignments",
    'main.support':             "Тех. поддержка",
    'main.tasks.list':          "Текущие задания",
    'main.tasks.create_task':   "Создать задание",
    'main.assignments.create_assignemnt':   "Create an assignment",
    'main.volunteers':          "Волонтеры",
    'main.volunteers.add_volunteer': "Добавить волонтера",
    'main.volunteers.list':     "Список волонтеров",
    'main.volunteers.active': "👥 Активные волонтеры",
    'main.volunteers.pending': "⏳ Волонтеры в ожидании",
    'volunteer.add.username': "Введите username пользователя (без @):",
    'volunteer.add.name': "Введите полное имя волонтера:",
    'volunteer.add.confirm': "Подтвердите добавление волонтера:\nUsername: @{}\nИмя: {}\n\nВсе верно?",
    'volunteer.add.success': "✅ Волонтер успешно добавлен",
    'volunteer.add.cancel': "❌ Добавление волонтера отменено",
    'go_back': "◀️ Назад",
    'select_day': "📅 Выбрать день",
}

LEXICON_COMMANDS_RU: dict[str, str] = {
    '/start': 'Запуск бота',
    '/help': 'Справка',
    '/change_roles': 'Switch admin<->volunteer',
    '/main_menu': "Главное меню",
    '/add_user': "/add_user {username} {role}",
    '/set_debug_time': "/set_debug_time 1 12:30",
    '/debug_status': "Show debug info"
}

LEXICON_VOLUNTEER_RU: dict[str, str] = {
    'add.username': "Введите username пользователя (без @):",
    'add.name': "Введите полное имя волонтера:",
    'add.confirm': "Подтвердите добавление волонтера:\nUsername: @{}\nИмя: {}\n\nВсе верно?",
    'add.success': "✅ Волонтер успешно добавлен",
    'add.cancel': "❌ Добавление волонтера отменено",
    'list.active': "👥 Активные волонтеры:\n\n{volunteers}",
    'list.pending': "⏳ Волонтеры в ожидании:\n\n{volunteers}",
    'list.empty': "Список пуст"
}